0: Starting numprocs=32 N=128, M=128 impl=allgather-async
12: Starting numprocs=32 N=128, M=128 impl=allgather-async
21: Starting numprocs=32 N=128, M=128 impl=allgather-async
9: Starting numprocs=32 N=128, M=128 impl=allgather-async
7: Starting numprocs=32 N=128, M=128 impl=allgather-async
24: Starting numprocs=32 N=128, M=128 impl=allgather-async
17: Starting numprocs=32 N=128, M=128 impl=allgather-async
29: Starting numprocs=32 N=128, M=128 impl=allgather-async
10: Starting numprocs=32 N=128, M=128 impl=allgather-async
20: Starting numprocs=32 N=128, M=128 impl=allgather-async
27: Starting numprocs=32 N=128, M=128 impl=allgather-async
16: Starting numprocs=32 N=128, M=128 impl=allgather-async
30: Starting numprocs=32 N=128, M=128 impl=allgather-async
8: Starting numprocs=32 N=128, M=128 impl=allgather-async
31: Starting numprocs=32 N=128, M=128 impl=allgather-async
23: Starting numprocs=32 N=128, M=128 impl=allgather-async
15: Starting numprocs=32 N=128, M=128 impl=allgather-async
14: Starting numprocs=32 N=128, M=128 impl=allgather-async
13: Starting numprocs=32 N=128, M=128 impl=allgather-async
25: Starting numprocs=32 N=128, M=128 impl=allgather-async
22: Starting numprocs=32 N=128, M=128 impl=allgather-async
18: Starting numprocs=32 N=128, M=128 impl=allgather-async
26: Starting numprocs=32 N=128, M=128 impl=allgather-async
19: Starting numprocs=32 N=128, M=128 impl=allgather-async
28: Starting numprocs=32 N=128, M=128 impl=allgather-async
3: Starting numprocs=32 N=128, M=128 impl=allgather-async
11: Starting numprocs=32 N=128, M=128 impl=allgather-async
4: Starting numprocs=32 N=128, M=128 impl=allgather-async
5: Starting numprocs=32 N=128, M=128 impl=allgather-async
1: Starting numprocs=32 N=128, M=128 impl=allgather-async
6: Starting numprocs=32 N=128, M=128 impl=allgather-async
2: Starting numprocs=32 N=128, M=128 impl=allgather-async
time: 0.111980s
Validation turned on
terminate called after throwing an instance of 'std::runtime_error'
  what():  Result of process 25 differs from result of process 0: error=788.401596
[eu-ms-001-15:25418] *** Process received signal ***
[eu-ms-001-15:25418] Signal: Aborted (6)
[eu-ms-001-15:25418] Signal code:  (-6)
[eu-ms-001-15:25418] [ 0] /usr/lib64/libpthread.so.0(+0xf630)[0x2b44f1e5b630]
[eu-ms-001-15:25418] [ 1] /usr/lib64/libc.so.6(gsignal+0x37)[0x2b44f209e387]
[eu-ms-001-15:25418] [ 2] /usr/lib64/libc.so.6(abort+0x148)[0x2b44f209fa78]
[eu-ms-001-15:25418] [ 3] /cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/gcc-9.3.0-mjmsvu3362usxjr7tas4ywkd2e4ko5x3/lib64/libstdc++.so.6(+0x99133)[0x2b44f15f1133]
[eu-ms-001-15:25418] [ 4] /cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/gcc-9.3.0-mjmsvu3362usxjr7tas4ywkd2e4ko5x3/lib64/libstdc++.so.6(+0xa4b56)[0x2b44f15fcb56]
[eu-ms-001-15:25418] [ 5] /cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/gcc-9.3.0-mjmsvu3362usxjr7tas4ywkd2e4ko5x3/lib64/libstdc++.so.6(+0xa4bc1)[0x2b44f15fcbc1]
[eu-ms-001-15:25418] [ 6] /cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/gcc-9.3.0-mjmsvu3362usxjr7tas4ywkd2e4ko5x3/lib64/libstdc++.so.6(+0xa4e14)[0x2b44f15fce14]
[eu-ms-001-15:25418] [ 7] code/build_output/main[0x40ae09]
[eu-ms-001-15:25418] [ 8] /usr/lib64/libc.so.6(__libc_start_main+0xf5)[0x2b44f208a555]
[eu-ms-001-15:25418] [ 9] code/build_output/main[0x40cc5f]
[eu-ms-001-15:25418] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node eu-ms-001-15 exited on signal 6 (Aborted).
--------------------------------------------------------------------------
